// Generated by Wrangler using `wrangler types`
// Manual definition of Cloudflare Workers environment bindings

interface Env {
  // Environment variables
  DATABASE_URL: string;
  POSTHOG_API_KEY: string;
  FRONTEND_URL: string;

  // R2 Object Storage
  STORAGE: R2Bucket;

  // Cloudflare Queue
  TASK_QUEUE: Queue;
}
